<?php
declare(strict_types=1);
require_once '../includes/security.php';
secureSessionStart();
requireRole(['admin']);
require_once '../config/database.php';
global $pdo;
$userId=filter_input(INPUT_GET,'user_id',FILTER_VALIDATE_INT);$action=trim((string)($_GET['action']??''));$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));
$conditions=['1=1'];$params=[];if($userId){$conditions[]='al.user_id=?';$params[]=$userId;}if($action!==''){$conditions[]='al.action LIKE ?';$params[]='%'.$action.'%';}if($from!==''){$conditions[]='al.created_at>=?';$params[]=$from.' 00:00:00';}if($to!==''){$conditions[]='al.created_at<=?';$params[]=$to.' 23:59:59';}
$stmt=$pdo->prepare('SELECT al.*,u.name user_name,u.email FROM audit_logs al LEFT JOIN users u ON u.id=al.user_id WHERE '.implode(' AND ',$conditions).' ORDER BY al.id DESC LIMIT 1000');$stmt->execute($params);$logs=$stmt->fetchAll();$users=$pdo->query('SELECT id,name,email FROM users ORDER BY name')->fetchAll();$page_title='Nhật ký hoạt động';require_once '../includes/header.php';
?>
<style>.audit-filter{display:grid;grid-template-columns:2fr 2fr 1fr 1fr auto;gap:10px;margin-bottom:18px}.audit-table{width:100%;border-collapse:collapse;min-width:900px}.audit-table th,.audit-table td{padding:12px;border-bottom:1px solid var(--border-color);text-align:left;vertical-align:top}.audit-table th{color:var(--text-muted)}.audit-context{max-width:420px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;color:var(--text-muted)}@media(max-width:900px){.audit-filter{grid-template-columns:1fr 1fr}}@media(max-width:560px){.audit-filter{grid-template-columns:1fr}}</style>
<h1><i class='bx bx-history'></i> Nhật ký hoạt động</h1><div class="box"><form class="audit-filter"><select name="user_id"><option value="">Mọi tài khoản</option><?php foreach($users as $u):?><option value="<?php echo $u['id'];?>" <?php echo $userId==$u['id']?'selected':'';?>><?php echo htmlspecialchars($u['name'].' · '.$u['email']);?></option><?php endforeach;?></select><input name="action" value="<?php echo htmlspecialchars($action);?>" placeholder="Hành động: submission, quiz..."><input type="date" name="from" value="<?php echo htmlspecialchars($from);?>"><input type="date" name="to" value="<?php echo htmlspecialchars($to);?>"><button class="btn btn-primary">Tra cứu</button></form><div style="overflow:auto"><table class="audit-table"><thead><tr><th>Thời gian</th><th>Người thực hiện</th><th>Hành động</th><th>Đối tượng</th><th>Chi tiết thay đổi</th><th>IP</th></tr></thead><tbody><?php foreach($logs as $log):$context=json_decode((string)($log['context_json']??''),true);?><tr><td><?php echo date('d/m/Y H:i:s',strtotime($log['created_at']));?></td><td><strong><?php echo htmlspecialchars($log['user_name']??'Hệ thống');?></strong><small style="display:block;color:var(--text-muted)"><?php echo htmlspecialchars($log['email']??'');?></small></td><td><code><?php echo htmlspecialchars($log['action']);?></code></td><td><?php echo htmlspecialchars(($log['entity_type']??'').' #'.($log['entity_id']??''));?></td><td><div class="audit-context"><?php echo htmlspecialchars($context?json_encode($context,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT):'—');?></div></td><td><?php echo htmlspecialchars($log['ip_address']??'');?></td></tr><?php endforeach;?><?php if(!$logs):?><tr><td colspan="6">Không có dữ liệu phù hợp.</td></tr><?php endif;?></tbody></table></div></div><?php require_once '../includes/footer.php';?>
