<?php
declare(strict_types=1);
require_once '../includes/security.php';
secureSessionStart();
requireRole(['admin']);
require_once '../config/database.php';
global $pdo;
$userId=filter_input(INPUT_GET,'user_id',FILTER_VALIDATE_INT);$action=trim((string)($_GET['action']??''));$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));
$conditions=['1=1'];$params=[];if($userId){$conditions[]='al.user_id=?';$params[]=$userId;}if($action!==''){$conditions[]='al.action LIKE ?';$params[]='%'.$action.'%';}if($from!==''){$conditions[]='al.created_at>=?';$params[]=$from.' 00:00:00';}if($to!==''){$conditions[]='al.created_at<=?';$params[]=$to.' 23:59:59';}
$whereSql=implode(' AND ',$conditions);$perPage=100;$countStmt=$pdo->prepare('SELECT COUNT(*) FROM audit_logs al WHERE '.$whereSql);$countStmt->execute($params);$totalLogs=(int)$countStmt->fetchColumn();$totalPages=max(1,(int)ceil($totalLogs/$perPage));$currentPage=max(1,min($totalPages,(int)($_GET['page']??1)));$offset=($currentPage-1)*$perPage;
$stmt=$pdo->prepare('SELECT al.id,al.user_id,al.action,al.entity_type,al.entity_id,al.context_json,al.ip_address,al.created_at,u.name user_name,u.email FROM audit_logs al LEFT JOIN users u ON u.id=al.user_id WHERE '.$whereSql.' ORDER BY al.id DESC LIMIT '.$perPage.' OFFSET '.$offset);$stmt->execute($params);$logs=$stmt->fetchAll();$users=$pdo->query('SELECT id,name,email FROM users ORDER BY name')->fetchAll();$pageUrl=static function(int $page):string{$query=$_GET;$query['page']=$page;return 'audit_logs.php?'.http_build_query($query);};$page_title='Nhật ký hoạt động';require_once '../includes/header.php';
?>
<style>
.audit-filter{display:grid;grid-template-columns:2fr 2fr 1fr 1fr auto;gap:12px;margin-bottom:18px;align-items:stretch}
.audit-filter select,.audit-filter input{width:100%;min-width:0;height:56px;padding:0 16px;border:1px solid rgba(148,163,184,.24);border-radius:12px;background:rgba(15,23,42,.76);color:var(--text-main);font:inherit;outline:none;color-scheme:dark;box-shadow:inset 0 1px 0 rgba(255,255,255,.025);transition:border-color .2s ease,box-shadow .2s ease,background .2s ease}
.audit-filter select{cursor:pointer;padding-right:38px}.audit-filter input::placeholder{color:var(--text-muted);opacity:.9}.audit-filter input:hover,.audit-filter select:hover{border-color:rgba(var(--primary-rgb),.5);background:rgba(15,23,42,.9)}.audit-filter input:focus,.audit-filter select:focus{border-color:var(--primary);background:rgba(15,23,42,.96);box-shadow:0 0 0 4px rgba(var(--primary-rgb),.14)}
.audit-filter input[type="date"]{position:relative;padding-right:42px}.audit-filter input[type="date"]::-webkit-calendar-picker-indicator{position:absolute;right:14px;width:19px;height:19px;cursor:pointer;filter:invert(1);opacity:.82}.audit-filter .btn{height:56px;padding:0 22px;white-space:nowrap;border-radius:12px}
.audit-table{width:100%;border-collapse:collapse;min-width:900px}.audit-table th,.audit-table td{padding:12px;border-bottom:1px solid var(--border-color);text-align:left;vertical-align:top}.audit-table th{color:var(--text-muted)}.audit-context{max-width:420px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;color:var(--text-muted)}
.audit-summary{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 14px;color:var(--text-muted)}.audit-pages{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:18px}.audit-pages .btn{min-width:44px;text-align:center}.audit-pages .is-disabled{pointer-events:none;opacity:.42}
@media(max-width:1100px){.audit-filter{grid-template-columns:1fr 1fr}.audit-filter .btn{width:100%}}
@media(max-width:560px){.audit-filter{grid-template-columns:1fr}}
</style>
<h1><i class='bx bx-history'></i> Nhật ký hoạt động</h1><div class="box"><form class="audit-filter"><select name="user_id"><option value="">Mọi tài khoản</option><?php foreach($users as $u):?><option value="<?php echo $u['id'];?>" <?php echo $userId==$u['id']?'selected':'';?>><?php echo htmlspecialchars($u['name'].' · '.$u['email']);?></option><?php endforeach;?></select><input name="action" value="<?php echo htmlspecialchars($action);?>" placeholder="Hành động: submission, quiz..."><input type="date" name="from" value="<?php echo htmlspecialchars($from);?>"><input type="date" name="to" value="<?php echo htmlspecialchars($to);?>"><button class="btn btn-primary">Tra cứu</button></form><div class="audit-summary"><span><?php echo number_format($totalLogs);?> hoạt động phù hợp</span><span>Trang <?php echo $currentPage;?>/<?php echo $totalPages;?></span></div><div style="overflow:auto"><table class="audit-table"><thead><tr><th>Thời gian</th><th>Người thực hiện</th><th>Hành động</th><th>Đối tượng</th><th>Chi tiết thay đổi</th><th>IP</th></tr></thead><tbody><?php foreach($logs as $log):$context=json_decode((string)($log['context_json']??''),true);?><tr><td><?php echo date('d/m/Y H:i:s',strtotime($log['created_at']));?></td><td><strong><?php echo htmlspecialchars($log['user_name']??'Hệ thống');?></strong><small style="display:block;color:var(--text-muted)"><?php echo htmlspecialchars($log['email']??'');?></small></td><td><code><?php echo htmlspecialchars($log['action']);?></code></td><td><?php echo htmlspecialchars(($log['entity_type']??'').' #'.($log['entity_id']??''));?></td><td><div class="audit-context"><?php echo htmlspecialchars($context?json_encode($context,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT):'—');?></div></td><td><?php echo htmlspecialchars($log['ip_address']??'');?></td></tr><?php endforeach;?><?php if(!$logs):?><tr><td colspan="6">Không có dữ liệu phù hợp.</td></tr><?php endif;?></tbody></table></div><?php if($totalPages>1):?><nav class="audit-pages"><a class="btn btn-outline <?php echo $currentPage<=1?'is-disabled':'';?>" href="<?php echo htmlspecialchars($pageUrl(max(1,$currentPage-1)));?>"><i class='bx bx-chevron-left'></i></a><?php for($page=max(1,$currentPage-2);$page<=min($totalPages,$currentPage+2);$page++):?><a class="btn <?php echo $page===$currentPage?'btn-primary':'btn-outline';?>" href="<?php echo htmlspecialchars($pageUrl($page));?>"><?php echo $page;?></a><?php endfor;?><a class="btn btn-outline <?php echo $currentPage>=$totalPages?'is-disabled':'';?>" href="<?php echo htmlspecialchars($pageUrl(min($totalPages,$currentPage+1)));?>"><i class='bx bx-chevron-right'></i></a></nav><?php endif;?></div><?php require_once '../includes/footer.php';?>
