<?php
declare(strict_types=1);
require_once '../config/database.php';
require_once '../includes/security.php';
secureSessionStart();
requireRole(['admin']);
require_once '../includes/backup_manager.php';
require_once '../includes/drive_inventory.php';
require_once '../includes/audit.php';

if(!isset($pdo)){throw new RuntimeException('Database connection not initialized.');}
$adminPasswordStmt=$pdo->prepare('SELECT password_hash FROM users WHERE id=?');$adminPasswordStmt->execute([(int)$_SESSION['user_id']]);$adminHasPassword=!empty($adminPasswordStmt->fetchColumn());
$backups=listBackups();$assetBackups=listLocalFileBackups();$latest=$backups[0]['created_at']??null;$warning=!$latest||$latest<time()-172800;
if(isset($_GET['download'])){$path=safeBackupPath((string)$_GET['download']);if(!$path){http_response_code(404);exit('Không tìm thấy bản sao lưu.');}header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="'.basename($path).'"');header('Content-Length: '.filesize($path));readfile($path);exit;}
if(isset($_GET['drive_export'])){$refs=collectDriveReferences($pdo);if($_GET['drive_export']==='verify')$refs=verifyDriveReferences($refs);header('Content-Type:text/csv;charset=UTF-8');header('Content-Disposition:attachment;filename="drive-inventory-'.date('Ymd-His').'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','wb');fputcsv($out,['Drive ID','Tên file','Nguồn tham chiếu','Trạng thái','Tên trên Drive']);foreach($refs as $r)fputcsv($out,[$r['drive_id'],$r['name'],implode('; ',$r['source']),$r['status']??'chưa kiểm tra',$r['drive_name']??'']);fclose($out);exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrfToken();$action=(string)($_POST['action']??'');$restoreTemp=null;try{if($action==='create'){$result=createDatabaseBackup($pdo);writeAuditLog($pdo,'backup.created','backup',null,['database'=>basename($result['database']),'assets'=>$result['assets']?basename($result['assets']):null]);$_SESSION['success']='Đã tạo bản sao lưu mới.';}elseif($action==='restore'){$user=$pdo->prepare('SELECT password_hash FROM users WHERE id=?');$user->execute([(int)$_SESSION['user_id']]);if(!password_verify((string)($_POST['password']??''),(string)$user->fetchColumn()))throw new RuntimeException('Mật khẩu Admin không đúng.');if((string)($_POST['confirmation']??'')!=='PHUC HOI')throw new RuntimeException('Vui lòng nhập đúng PHUC HOI để xác nhận.');$path=safeBackupPath((string)($_POST['backup_name']??''));if(!$path||!str_contains(basename($path),'database'))throw new RuntimeException('Bản sao lưu không hợp lệ.');$restoreTemp=backupDirectory().DIRECTORY_SEPARATOR.'.restore_'.bin2hex(random_bytes(8)).(str_ends_with($path,'.gz')?'.sql.gz':'.sql');if(!copy($path,$restoreTemp))throw new RuntimeException('Không thể chuẩn bị file phục hồi.');createDatabaseBackup($pdo);restoreDatabaseBackup($pdo,$restoreTemp);writeAuditLog($pdo,'backup.restored','backup',null,['file'=>basename($path)]);$_SESSION['success']='Đã phục hồi cơ sở dữ liệu.';}}catch(Throwable $e){$_SESSION['error']=$e->getMessage();}finally{if($restoreTemp&&is_file($restoreTemp))@unlink($restoreTemp);}header('Location: backups.php');exit;}
$page_title='Sao lưu và phục hồi';require_once '../includes/header.php';
?>
<style>.backup-grid{display:grid;grid-template-columns:1.25fr .75fr;gap:18px}.backup-card{padding:20px}.backup-list{display:grid;gap:10px}.backup-item{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:14px;border:1px solid var(--border-color);border-radius:12px;background:var(--input-bg)}.backup-form{display:grid;gap:12px}.backup-form input,.backup-form select{height:52px;padding:0 14px;border:1px solid var(--border-color);border-radius:11px;background:var(--input-bg);color:var(--text-main);font:inherit;outline:none}.backup-form input:focus,.backup-form select:focus{border-color:var(--primary);box-shadow:0 0 0 3px rgba(var(--primary-rgb),.15)}@media(max-width:900px){.backup-grid{grid-template-columns:1fr}}</style>
<h1><i class='bx bx-data'></i> Sao lưu và phục hồi</h1><?php if(isset($_SESSION['success'])):?><div class="alert alert-success"><?php echo htmlspecialchars($_SESSION['success']);unset($_SESSION['success']);?></div><?php endif;?><?php if(isset($_SESSION['error'])):?><div class="alert alert-danger"><?php echo htmlspecialchars($_SESSION['error']);unset($_SESSION['error']);?></div><?php endif;?><?php if(!$adminHasPassword):?><div class="alert alert-danger" style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><span><strong>Tài khoản Google chưa có mật khẩu LMS.</strong> Bạn cần đặt mật khẩu trước khi sử dụng chức năng phục hồi.</span><a class="btn btn-primary" href="../account/profile.php#lms-password"><i class='bx bx-key'></i> Đặt mật khẩu LMS</a></div><?php endif;?><?php if($warning):?><div class="alert alert-danger"><strong>Cảnh báo:</strong> Hệ thống chưa có bản sao lưu trong 2 ngày gần đây.</div><?php endif;?>
<div class="backup-grid"><main class="box backup-card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h2 style="margin:0 0 6px">Các bản database</h2><small style="color:var(--text-muted)">Tự động chỉ giữ 5 bản gần nhất.</small></div><form method="post"><?php echo csrfField();?><input type="hidden" name="action" value="create"><button class="btn btn-primary"><i class='bx bx-plus'></i> Sao lưu ngay</button></form></div><div class="backup-list" style="margin-top:18px"><?php foreach($backups as $backup):?><div class="backup-item"><div><strong><?php echo htmlspecialchars($backup['name']);?></strong><small style="display:block;color:var(--text-muted);margin-top:4px"><?php echo date('d/m/Y H:i',$backup['created_at']);?> · <?php echo number_format($backup['size']/1048576,2);?> MB</small></div><a class="btn btn-outline" href="?download=<?php echo urlencode($backup['name']);?>"><i class='bx bx-download'></i> Tải</a></div><?php endforeach;?><?php if(!$backups):?><p style="color:var(--text-muted)">Chưa có bản sao lưu.</p><?php endif;?></div><h2 style="margin-top:26px">File cục bộ</h2><p style="color:var(--text-muted)">Chỉ gồm nội dung trong uploads chưa nằm trên Drive; luôn bỏ qua uploads/temp_ai.</p><div class="backup-list"><?php foreach($assetBackups as $backup):?><div class="backup-item"><div><strong><?php echo htmlspecialchars($backup['name']);?></strong><small style="display:block;color:var(--text-muted);margin-top:4px"><?php echo date('d/m/Y H:i',$backup['created_at']);?> · <?php echo number_format($backup['size']/1048576,2);?> MB</small></div><a class="btn btn-outline" href="?download=<?php echo urlencode($backup['name']);?>"><i class='bx bx-download'></i> Tải</a></div><?php endforeach;?><?php if(!$assetBackups):?><p style="color:var(--text-muted)">Chưa có file cục bộ cần sao lưu hoặc máy chủ chưa bật ZipArchive.</p><?php endif;?></div></main>
<aside><section class="box backup-card"><h2 style="margin-top:0">Phục hồi database</h2><p style="color:var(--text-muted)">Hệ thống sẽ tự sao lưu trạng thái hiện tại trước khi phục hồi.</p><form method="post" class="backup-form" onsubmit="return confirm('Phục hồi sẽ thay thế dữ liệu hiện tại. Bạn chắc chắn tiếp tục?')"><?php echo csrfField();?><input type="hidden" name="action" value="restore"><select name="backup_name" required><option value="">Chọn bản sao lưu</option><?php foreach($backups as $backup):?><option><?php echo htmlspecialchars($backup['name']);?></option><?php endforeach;?></select><input type="password" name="password" placeholder="Mật khẩu Admin" required autocomplete="current-password"><input name="confirmation" placeholder="Nhập PHUC HOI" required><button class="btn btn-outline" style="color:var(--danger)"><i class='bx bx-reset'></i> Phục hồi</button></form></section><section class="box backup-card" style="margin-top:18px"><h2 style="margin-top:0">Google Drive</h2><p style="color:var(--text-muted)">Xuất toàn bộ Drive ID hoặc kiểm tra file còn tồn tại. Xóa file trong LMS mặc định chỉ chuyển vào Thùng rác.</p><div class="alert alert-success" style="margin:12px 0">Nên kết nối bằng một tài khoản Drive riêng của trung tâm, chỉ cấp quyền quản lý cho Admin và bật xác minh hai bước cho tài khoản đó.</div><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn btn-outline" href="?drive_export=list"><i class='bx bx-list-ul'></i> Xuất Drive ID</a><a class="btn btn-primary" href="?drive_export=verify"><i class='bx bx-check-shield'></i> Kiểm tra và xuất</a></div></section></aside></div>
<?php require_once '../includes/footer.php';?>
